apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-postgres-test
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        cascadingDelete: true
        highAvailability: true
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: db-custom-1-3840
        databases:
          - name: postgres-test
            envVarPrefix: DB
