/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    if (PostgresDataSourceBuilder.dataSource.isRunning) {
        println("PostgresDataSourceBuilder is running")
    } else {
        println("PostgresDataSourceBuilder is not running")
    }
    PostgresDataSourceBuilder.dataSource.use { dataSource ->
        dataSource.connection.use { connection ->
            connection.createStatement().use { statement ->
                statement.executeQuery("SELECT 1").use { resultSet ->
                    while (resultSet.next()) {
                        println(resultSet.getInt(1))
                    }
                }
            }
        }
    }
}
