/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.PostgresDataSourceBuilder.dataSource
import org.example.PostgresDataSourceBuilder.runMigration

fun main() {
    // Kjør migreringer
    runMigration()

    dataSource.use { dataSource ->
        dataSource.connection.use { connection ->
            connection.createStatement().use { statement ->
                statement.executeQuery("SELECT 1").use { resultSet ->
                    while (resultSet.next()) {
                        println(resultSet.getInt(1))
                    }
                }
            }
        }
    }
}
