/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    if (PostgresDataSourceBuilder.dataSource.isRunning) {
        println("PostgresDataSourceBuilder is running")
    } else {
        println("PostgresDataSourceBuilder is not running")
    }
}
