[versions]
hikaricp = "5.1.0"
postgresql = "42.7.2"

[libraries]
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
postgresql-driver = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.22" }
